# 使用 ijkl 上左下右

keybinding:
  universal:
    prevItem-alt: 'i' # go one line up
    nextItem-alt: 'k' # go one line down
    scrollLeft: 'J' # scroll left within list view
    prevBlock-alt: 'j' # goto the previous block / panel
    scrollUpMain-alt1: 'I' # main panel scroll up
    scrollDownMain-alt1: 'K' # main panel scroll down
  files:
    ignoreFile: 'h'
  branches:
    viewGitFlowOptions: 'h'
  submodules:
    init: 'h'
