# 注意版本控制系统和显示信息
set vcs_aware true

set preview_images true
set preview_images_method ueberzug

set cd_tab_case insensitive
set cd_tab_fuzzy true

set line_numbers relative

# 使用 ijkl 上左下右
copymap <UP>    i
copymap <DOWN>  k
copymap <LEFT>  j
copymap <RIGHT> l
