;;; 模态编辑：猫态编辑
;;
;; 键位使用李杀的飞键键位

(use-package meow
  :config
  (defun meow-setup ()                  ; 按键绑定
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
    (meow-motion-overwrite-define-key
     '("i" . meow-prev)
     '("k" . meow-next)
     '("<escape>" . ignore))

    ;; 领导键映射，包括 mode-specific-map
    (meow-leader-define-key
     ;; high frequency keybindings
     '("," . xref-pop-marker-stack)
     '("." . xref-find-definitions)
     '(";" . comment-dwim)
     '("b" . switch-to-buffer)
     '("d" . dired)
     '("e" . "C-x C-e")
     '("f" . find-file)
     '("i" . imenu)
     '("j" . project-switch-to-buffer)
     '("k" . kill-this-buffer)
     '("o" . delete-other-windows)
     '("p" . project-find-file)
     '("s" . split-window-right)
     '("u" . meow-universal-argument)
     '("v" . split-window-below)
     '("w" . other-window)
     '("W" . window-swap-states)

     ;; Use SPC (0-9) for digit arguments.
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument)
     '("/" . meow-keypad-describe-key)
     '("?" . meow-cheatsheet))

    (meow-normal-define-key
     '("`" . other-frame)
     '("1" . xah-extend-selection)
     '("2" . ignore)
     '("3" . delete-other-windows)
     '("4" . split-window-below)
     '("5" . delete-char)
     '("6" . xah-select-block)
     '("7" . xah-select-line)
     '("8" . xah-extend-selection)
     '("9" . xah-select-text-in-quote)
     '("0" . xah-pop-local-mark-ring)
     '("-" . xah-backward-punct)
     '("=" . xah-forward-punct)
     '("q" . xah-reformat-lines)
     '("w" . xah-shrink-whitespaces)
     '("e" . backward-kill-word)
     '("r" . kill-word)
     '("t" . set-mark-command)
     '("y" . undo)
     '("u" . backward-word)
     '("i" . previous-line)
     '("o" . forward-word)
     '("p" . xah-insert-space-before)
     '("[" . hippie-expand)
     '("]" . ignore)
     '("a" . execute-extended-command)
     '("s" . open-line)
     '("d" . xah-delete-backward-char-or-bracket-text)
     '("f" . meow-insert)
     '("g" . xah-delete-current-text-block)
     '("h" . xah-beginning-of-line-or-block)
     '("j" . backward-char)
     '("k" . next-line)
     '("l" . forward-char)
     '(";" . xah-end-of-line-or-block)
     '("'" . xah-cycle-hyphen-lowline-space)
     '("z" . xah-comment-dwim)
     '("x" . xah-cut-line-or-region)
     '("c" . xah-copy-line-or-region)
     '("v" . xah-paste-or-paste-previous)
     '("b" . xah-toggle-letter-case)
     '("n" . isearch-forward)
     '("m" . xah-backward-left-bracket)
     '("," . xah-next-window-or-frame)
     '("." . xah-forward-right-bracket)
     '("/" . xah-goto-matching-bracket)

     '("<escape>" . ignore)))

  (meow-setup)
  (meow-global-mode 1))

(provide 'init-meow)
